CrossJunctionNavigation:
    trainer: ppo
    max_steps: 1e6
    time_horizon: 128
    keep_checkpoints: 5
    summary_freq: 50000
    threaded: false
    batch_size: 1024
    buffer_size: 10240
    learning_rate: 3e-4
    learning_rate_schedule: linear
    beta: 5e-3
    epsilon: 0.2
    lambd: 0.97
    num_epoch: 3
    normalize: false
    hidden_units: 128
    num_layers: 3
    use_recurrent: false
    memory_size: 0
    sequence_length: 0
    vis_encode_type: simple
    reward_signals:
      extrinsic:
        strength: 1.0
        gamma: 0.99
